<?php
/*********************
12-01-2003  v3.01
Module:  Module  Include
Called from:  calendar_input.php
Description:  state and country drop down menus
To Do: 

*********************/ 
# Drop Downs
$countryDropDown2 = '<option value=""><b>Select A Country</b></option>
<option value="United States">United States</option>
<option value="Canada">Canada</option>
<option value="Afganistan">Afghanistan</option>
<option value="Albania">Albania</option>
<option value="Algeria">Algeria</option>
<option value="American Samoa">American Samoa</option>
<option value="Andorra">Andorra</option>
<option value="Angola">Angola</option>
<option value="Anguilla">Anguilla</option>
<option value="Antigua & Barbuda">Antigua & Barbuda</option>
<option value="Argentina">Argentina</option>
<option value="Armenia">Armenia</option>
<option value="Aruba">Aruba</option>
<option value="Australia">Australia</option>
<option value="Austria">Austria</option>
<option value="Azerbaijan">Azerbaijan</option>
<option value="Azores">Azores</option>
<option value="Bahamas">Bahamas</option>
<option value="Bahrain">Bahrain</option>
<option value="Bangladesh">Bangladesh</option>
<option value="Barbados">Barbados</option>
<option value="Belarus">Belarus</option>
<option value="Belgium">Belgium</option>
<option value="Belize">Belize</option>
<option value="Benin">Benin</option>
<option value="Bermuda">Bermuda</option>
<option value="Bhutan">Bhutan</option>
<option value="Bolivia">Bolivia</option>
<option value="Bonaire">Bonaire</option>
<option value="Bosnia & Herzegovina">Bosnia & Herzegovina</option>
<option value="Botswana">Botswana</option>
<option value="Brazil">Brazil</option>
<option value="British Indian Ocean Ter">British Indian Ocean Ter</option>
<option value="Brunei">Brunei</option>
<option value="Bulgaria">Bulgaria</option>
<option value="Burkina Faso">Burkina Faso</option>
<option value="Burundi">Burundi</option>
<option value="Cambodia">Cambodia</option>
<option value="Cameroon">Cameroon</option>
<option value="Canada">Canada</option>
<option value="Canary Islands">Canary Islands</option>
<option value="Cape Verde">Cape Verde</option>
<option value="Cayman Islands">Cayman Islands</option>
<option value="Central African Republic">Central African Republic</option>
<option value="Chad">Chad</option>
<option value="Channel Islands">Channel Islands</option>
<option value="Chile">Chile</option>
<option value="China">China</option>
<option value="Christmas Island">Christmas Island</option>
<option value="Cocos Island">Cocos Island</option>
<option value="Columbia">Columbia</option>
<option value="Comoros">Comoros</option>
<option value="Congo">Congo</option>
<option value="Cook Islands">Cook Islands</option>
<option value="Costa Rica">Costa Rica</option>
<option value="Cote DIvoire">Cote D\'Ivoire</option>
<option value="Croatia">Croatia</option>
<option value="Cuba">Cuba</option>
<option value="Curaco">Curacao</option>
<option value="Cyprus">Cyprus</option>
<option value="Czech Republic">Czech Republic</option>
<option value="Denmark">Denmark</option>
<option value="Djibouti">Djibouti</option>
<option value="Dominica">Dominica</option>
<option value="Dominican Republic">Dominican Republic</option>
<option value="East Timor">East Timor</option>
<option value="Ecuador">Ecuador</option>
<option value="Egypt">Egypt</option>
<option value="El Salvador">El Salvador</option>
<option value="Equatorial Guinea">Equatorial Guinea</option>
<option value="Eritrea">Eritrea</option>
<option value="Estonia">Estonia</option>
<option value="Ethiopia">Ethiopia</option>
<option value="Falkland Islands">Falkland Islands</option>
<option value="Faroe Islands">Faroe Islands</option>
<option value="Fiji">Fiji</option>
<option value="Finland">Finland</option>
<option value="France">France</option>
<option value="French Guiana">French Guiana</option>
<option value="French Polynesia">French Polynesia</option>
<option value="French Southern Ter">French Southern Ter</option>
<option value="Gabon">Gabon</option>
<option value="Gambia">Gambia</option>
<option value="Georgia">Georgia</option>
<option value="Germany">Germany</option>
<option value="Ghana">Ghana</option>
<option value="Gibraltar">Gibraltar</option>
<option value="Great Britain">Great Britain</option>
<option value="Greece">Greece</option>
<option value="Greenland">Greenland</option>
<option value="Grenada">Grenada</option>
<option value="Guadeloupe">Guadeloupe</option>
<option value="Guam">Guam</option>
<option value="Guatemala">Guatemala</option>
<option value="Guinea">Guinea</option>
<option value="Guyana">Guyana</option>
<option value="Haiti">Haiti</option>
<option value="Hawaii">Hawaii</option>
<option value="Honduras">Honduras</option>
<option value="Hong Kong">Hong Kong</option>
<option value="Hungary">Hungary</option>
<option value="Iceland">Iceland</option>
<option value="India">India</option>
<option value="Indonesia">Indonesia</option>
<option value="Iran">Iran</option>
<option value="Iraq">Iraq</option>
<option value="Ireland">Ireland</option>
<option value="Isle of Man">Isle of Man</option>
<option value="Israel">Israel</option>
<option value="Italy">Italy</option>
<option value="Jamaica">Jamaica</option>
<option value="Japan">Japan</option>
<option value="Jordan">Jordan</option>
<option value="Kazakhstan">Kazakhstan</option>
<option value="Kenya">Kenya</option>
<option value="Kiribati">Kiribati</option>
<option value="Korea North">Korea North</option>
<option value="Korea Sout">Korea South</option>
<option value="Kuwait">Kuwait</option>
<option value="Kyrgyzstan">Kyrgyzstan</option>
<option value="Laos">Laos</option>
<option value="Latvia">Latvia</option>
<option value="Lebanon">Lebanon</option>
<option value="Lesotho">Lesotho</option>
<option value="Liberia">Liberia</option>
<option value="Libya">Libya</option>
<option value="Liechtenstein">Liechtenstein</option>
<option value="Lithuania">Lithuania</option>
<option value="Luxembourg">Luxembourg</option>
<option value="Macau">Macau</option>
<option value="Macedonia">Macedonia</option>
<option value="Madagascar">Madagascar</option>
<option value="Malaysia">Malaysia</option>
<option value="Malawi">Malawi</option>
<option value="Maldives">Maldives</option>
<option value="Mali">Mali</option>
<option value="Malta">Malta</option>
<option value="Marshall Islands">Marshall Islands</option>
<option value="Martinique">Martinique</option>
<option value="Mauritania">Mauritania</option>
<option value="Mauritius">Mauritius</option>
<option value="Mayotte">Mayotte</option>
<option value="Mexico">Mexico</option>
<option value="Midway Islands">Midway Islands</option>
<option value="Moldova">Moldova</option>
<option value="Monaco">Monaco</option>
<option value="Mongolia">Mongolia</option>
<option value="Montserrat">Montserrat</option>
<option value="Morocco">Morocco</option>
<option value="Mozambique">Mozambique</option>
<option value="Myanmar">Myanmar</option>
<option value="Nambia">Nambia</option>
<option value="Nauru">Nauru</option>
<option value="Nepal">Nepal</option>
<option value="Netherland Antilles">Netherland Antilles</option>
<option value="Netherlands">Netherlands</option>
<option value="Nevis">Nevis</option>
<option value="New Caledonia">New Caledonia</option>
<option value="New Zealand">New Zealand</option>
<option value="Nicaragua">Nicaragua</option>
<option value="Niger">Niger</option>
<option value="Nigeria">Nigeria</option>
<option value="Niue">Niue</option>
<option value="Norfolk Island">Norfolk Island</option>
<option value="Norway">Norway</option>
<option value="Oman">Oman</option>
<option value="Pakistan">Pakistan</option>
<option value="Palau Island">Palau Island</option>
<option value="Palestine">Palestine</option>
<option value="Panama">Panama</option>
<option value="Papua New Guinea">Papua New Guinea</option>
<option value="Paraguay">Paraguay</option>
<option value="Peru">Peru</option>
<option value="Phillipines">Philippines</option>
<option value="Pitcairn Island">Pitcairn Island</option>
<option value="Poland">Poland</option>
<option value="Portugal">Portugal</option>
<option value="Puerto Rico">Puerto Rico</option>
<option value="Qatar">Qatar</option>
<option value="Reunion">Reunion</option>
<option value="Romania">Romania</option>
<option value="Russia">Russia</option>
<option value="Rwanda">Rwanda</option>
<option value="St Barthelemy">St Barthelemy</option>
<option value="St Eustatius">St Eustatius</option>
<option value="St Helena">St Helena</option>
<option value="St Kitts-Nevis">St Kitts-Nevis</option>
<option value="St Lucia">St Lucia</option>
<option value="St Maarten">St Maarten</option>
<option value="St Pierre & Miquelon">St Pierre & Miquelon</option>
<option value="St Vincent & Grenadines">St Vincent & Grenadines</option>
<option value="Saipan">Saipan</option>
<option value="Samoa">Samoa</option>
<option value="Samoa American">Samoa American</option>
<option value="San Marino">San Marino</option>
<option value="Sao Tome & Principe">Sao Tome & Principe</option>
<option value="Saudi Arabia">Saudi Arabia</option>
<option value="Senegal">Senegal</option>
<option value="Seychelles">Seychelles</option>
<option value="Serbia & Montenegro">Serbia & Montenegro</option>
<option value="Sierra Leone">Sierra Leone</option>
<option value="Singapore">Singapore</option>
<option value="Slovakia">Slovakia</option>
<option value="Slovenia">Slovenia</option>
<option value="Solomon Islands">Solomon Islands</option>
<option value="Somalia">Somalia</option>
<option value="South Africa">South Africa</option>
<option value="Spain">Spain</option>
<option value="Sri Lanka">Sri Lanka</option>
<option value="Sudan">Sudan</option>
<option value="Suriname">Suriname</option>
<option value="Swaziland">Swaziland</option>
<option value="Sweden">Sweden</option>
<option value="Switzerland">Switzerland</option>
<option value="Syria">Syria</option>
<option value="Tahiti">Tahiti</option>
<option value="Taiwan">Taiwan</option>
<option value="Tajikistan">Tajikistan</option>
<option value="Tanzania">Tanzania</option>
<option value="Thailand">Thailand</option>
<option value="Togo">Togo</option>
<option value="Tokelau">Tokelau</option>
<option value="Tonga">Tonga</option>
<option value="Trinidad & Tobago">Trinidad & Tobago</option>
<option value="Tunisia">Tunisia</option>
<option value="Turkey">Turkey</option>
<option value="Turkmenistan">Turkmenistan</option>
<option value="Turks & Caicos Is">Turks & Caicos Is</option>
<option value="Tuvalu">Tuvalu</option>
<option value="Uganda">Uganda</option>
<option value="Ukraine">Ukraine</option>
<option value="United Arab Erimates">United Arab Emirates</option>
<option value="United States">United States</option>
<option value="Uraguay">Uruguay</option>
<option value="Uzbekistan">Uzbekistan</option>
<option value="Vanuatu">Vanuatu</option>
<option value="Vatican City State">Vatican City State</option>
<option value="Venezuela">Venezuela</option>
<option value="Vietnam">Vietnam</option>
<option value="Virgin Islands (Brit)">Virgin Islands (Brit)</option>
<option value="Virgin Islands (USA)">Virgin Islands (USA)</option>
<option value="Wake Island">Wake Island</option>
<option value="Wallis & Futana Is">Wallis & Futana Is</option>
<option value="Yemen">Yemen</option>
<option value="Zaire">Zaire</option>
<option value="Zambia">Zambia</option>
<option value="Zimbabwe">Zimbabwe</option>';

$countryDropDown = '<option value=""><b>Select A Country</b></option>
<option value="USA" SELECTED>United States</option>
<option value="CAN">Canada</option>
<option value="GBR">United Kingdom</option>
<option value="AFG" >Afghanistan</option>
<option value="ALB" >Albania</option>
<option value="DZA" >Algeria</option>
<option value="ASM" >American Samoa</option>
<option value="AND" >Andorra</option>
<option value="AGO" >Angola</option>
<option value="AIA" >Anguilla</option>
<option value="ATG" >Antigua and Barbuda</option>
<option value="ARG" >Argentina</option>
<option value="ARM" >Armenia</option>
<option value="ABW" >Aruba</option>
<option value="AUS" >Australia</option>
<option value="AUT" >Austria</option>
<option value="AZE" >Azerbaijan</option>
<option value="BHS" >Bahamas</option>
<option value="BHR" >Bahrain</option>
<option value="BGD" >Bangladesh</option>
<option value="BRB" >Barbados</option>
<option value="BLR" >Belarus</option>
<option value="BEL" >Belgium</option>
<option value="BLZ" >Belize</option>
<option value="BEN" >Benin</option>
<option value="BMU" >Bermuda</option>
<option value="BTN" >Bhutan</option>
<option value="BOL" >Bolivia</option>
<option value="BIH" >Bosnia and Herzegovina</option>
<option value="BWA" >Botswana</option>
<option value="BRA" >Brazil</option>
<option value="VGB" >British Virgin Islands</option>
<option value="BRN" >Brunei Darussalam</option>
<option value="BGR" >Bulgaria</option>
<option value="BFA" >Burkina Faso</option>
<option value="BDI" >Burundi</option>
<option value="KHM" >Cambodia</option>
<option value="CMR" >Cameroon</option>
<option value="CAN" >Canada</option>
<option value="CPV" >Cape Verde</option>
<option value="CYM" >Cayman Islands</option>
<option value="CAF" >Central African Republic</option>
<option value="TCD" >Chad</option>
<option value="CHL" >Chile</option>
<option value="CHN" >China</option>
<option value="COL" >Colombia</option>
<option value="COM" >Comoros</option>
<option value="COG" >Congo</option>
<option value="COK" >Cook Islands</option>
<option value="CRI" >Costa Rica</option>
<option value="CIV" >Cote d\'Ivoire</option>
<option value="HRV" >Croatia</option>
<option value="CUB" >Cuba</option>
<option value="CYP" >Cyprus</option>
<option value="CZE" >Czech Republic</option>
<option value="DNK" >Denmark</option>
<option value="DJI" >Djibouti</option>
<option value="DMA" >Dominica</option>
<option value="DOM" >Dominican Republic</option>
<option value="TMP" >East Timor</option>
<option value="ECU" >Ecuador</option>
<option value="EGY" >Egypt</option>
<option value="SLV" >El Salvador</option>
<option value="GNQ" >Equatorial Guinea</option>
<option value="ERI" >Eritrea</option>
<option value="EST" >Estonia</option>
<option value="ETH" >Ethiopia</option>
<option value="FRO" >Faeroe Islands</option>
<option value="FLK" >Falkland Islands</option>
<option value="FJI" >Fiji</option>
<option value="FIN" >Finland</option>
<option value="FRA" >France</option>
<option value="GUF" >French Guiana</option>
<option value="PYF" >French Polynesia</option>
<option value="GAB" >Gabon</option>
<option value="GMB" >Gambia</option>
<option value="GEO" >Georgia</option>
<option value="DEU" >Germany</option>
<option value="GHA" >Ghana</option>
<option value="GIB" >Gibraltar</option>
<option value="GRC" >Greece</option>
<option value="GRL" >Greenland</option>
<option value="GRD" >Grenada</option>
<option value="GLP" >Guadeloupe</option>
<option value="GUM" >Guam</option>
<option value="GTM" >Guatemala</option>
<option value="GIN" >Guinea</option>
<option value="GNB" >Guinea-Bissau</option>
<option value="GUY" >Guyana</option>
<option value="HTI" >Haiti</option>
<option value="VAT" >Holy See</option>
<option value="HND" >Honduras</option>
<option value="HKG" >Hong Kong</option>
<option value="HUN" >Hungary</option>
<option value="ISL" >Iceland</option>
<option value="IND" >India</option>
<option value="IDN" >Indonesia</option>
<option value="IRN" >Iran</option>
<option value="IRQ" >Iraq</option>
<option value="IRL" >Ireland</option>
<option value="ISR" >Israel</option>
<option value="ITA" >Italy</option>
<option value="JAM" >Jamaica</option>
<option value="JPN" >Japan</option>
<option value="JOR" >Jordan</option>
<option value="KAZ" >Kazakhstan</option>
<option value="KEN" >Kenya</option>
<option value="KIR" >Kiribati</option>
<option value="KWT" >Kuwait</option>
<option value="KGZ" >Kyrgyzstan</option>
<option value="LAO" >Lao</option>
<option value="LVA" >Latvia</option>
<option value="LBN" >Lebanon</option>
<option value="LSO" >Lesotho</option>
<option value="LBR" >Liberia</option>
<option value="LBY" >Libyan Arab Jamahiriya</option>
<option value="LIE" >Liechtenstein</option>
<option value="LTU" >Lithuania</option>
<option value="LUX" >Luxembourg</option>
<option value="MAC" >Macao</option>
<option value="MKD" >Macedonia</option>
<option value="MDG" >Madagascar</option>
<option value="MWI" >Malawi</option>
<option value="MYS" >Malaysia</option>
<option value="MDV" >Maldives</option>
<option value="MLI" >Mali</option>
<option value="MLT" >Malta</option>
<option value="MHL" >Marshall Islands</option>
<option value="MTQ" >Martinique</option>
<option value="MRT" >Mauritania</option>
<option value="MUS" >Mauritius</option>
<option value="MEX" >Mexico</option>
<option value="FSM" >Micronesia</option>
<option value="MCO" >Monaco</option>
<option value="MNG" >Mongolia</option>
<option value="MSR" >Montserrat</option>
<option value="MAR" >Morocco</option>
<option value="MOZ" >Mozambique</option>
<option value="MMR" >Myanmar</option>
<option value="NAM" >Namibia</option>
<option value="NRU" >Nauru</option>
<option value="NPL" >Nepal</option>
<option value="NLD" >Netherlands</option>
<option value="ANT" >Netherlands Antilles</option>
<option value="NCL" >New Caledonia</option>
<option value="NZL" >New Zealand</option>
<option value="NIC" >Nicaragua</option>
<option value="NER" >Niger</option>
<option value="NGA" >Nigeria</option>
<option value="NIU" >Niue</option>
<option value="NFK" >Norfolk Island</option>
<option value="PRK" >North Korea</option>
<option value="MNP" >Northern Mariana Islands</option>
<option value="NOR" >Norway</option>
<option value="OMN" >Oman</option>
<option value="PAK" >Pakistan</option>
<option value="PLW" >Palau</option>
<option value="PSE" >Palestinian Territory</option>
<option value="PAN" >Panama</option>
<option value="PNG" >Papua New Guinea</option>
<option value="PRY" >Paraguay</option>
<option value="PER" >Peru</option>
<option value="PHL" >Philippines</option>
<option value="PCN" >Pitcairn</option>
<option value="POL" >Poland</option>
<option value="PRT" >Portugal</option>
<option value="PRI" >Puerto Rico</option>
<option value="QAT" >Qatar</option>
<option value="MDA" >Republic of Moldova</option>
<option value="REU" >Réunion</option>
<option value="ROM" >Romania</option>
<option value="RUS" >Russian Federation</option>
<option value="RWA" >Rwanda</option>
<option value="SHN" >Saint Helena</option>
<option value="KNA" >Saint Kitts and Nevis</option>
<option value="LCA" >Saint Lucia</option>
<option value="SPM" >Saint Pierre and Miquelon</option>
<option value="VCT" >Saint Vincent/Grenadines</option>
<option value="WSM" >Samoa</option>
<option value="SMR" >San Marino</option>
<option value="STP" >Sao Tome and Principe</option>
<option value="SAU" >Saudi Arabia</option>
<option value="SEN" >Senegal</option>
<option value="SYC" >Seychelles</option>
<option value="SLE" >Sierra Leone</option>
<option value="SGP" >Singapore</option>
<option value="SVK" >Slovakia</option>
<option value="SVN" >Slovenia</option>
<option value="SLB" >Solomon Islands</option>
<option value="SOM" >Somalia</option>
<option value="ZAF" >South Africa</option>
<option value="KOR" >South Korea</option>
<option value="ESP" >Spain</option>
<option value="LKA" >Sri Lanka</option>
<option value="SDN" >Sudan</option>
<option value="SUR" >Suriname</option>
<option value="SWZ" >Swaziland</option>
<option value="SWE" >Sweden</option>
<option value="CHE" >Switzerland</option>
<option value="SYR" >Syrian Arab Republic</option>
<option value="TWN" >Taiwan Province of China</option>
<option value="TJK" >Tajikistan</option>
<option value="TZA" >Tanzania</option>
<option value="THA" >Thailand</option>
<option value="TGO" >Togo</option>
<option value="TKL" >Tokelau</option>
<option value="TON" >Tonga</option>
<option value="TTO" >Trinidad and Tobago</option>
<option value="TUN" >Tunisia</option>
<option value="TUR" >Turkey</option>
<option value="TKM" >Turkmenistan</option>
<option value="TCA" >Turks and Caicos Islands</option>
<option value="TUV" >Tuvalu</option>
<option value="UGA" >Uganda</option>
<option value="UKR" >Ukraine</option>
<option value="ARE" >United Arab Emirates</option>
<option value="GBR" >United Kingdom</option>
<option value="USA" >United States</option>
<option value="URY" >Uruguay</option>
<option value="VIR" >US Virgin Islands</option>
<option value="UZB" >Uzbekistan</option>
<option value="VUT" >Vanuatu</option>
<option value="VEN" >Venezuela</option>
<option value="VNM" >Viet Nam</option>
<option value="WLF" >Wallis and Futuna Islands</option>
<option value="ESH" >Western Sahara</option>
<option value="YEM" >Yemen</option>
<option value="YUG" >Yugoslavia</option>
<option value="ZMB" >Zambia</option>
<option value="ZWE" >Zimbabwe</option>';

/* $StateDropDown = '<option><b>**Select State</b></option>
			<OPTION VALUE="AL">Alabama</OPTION>
			<OPTION VALUE="AK">Alaska</OPTION>
			<OPTION VALUE="AZ">Arizona</OPTION>
			<OPTION VALUE="AR">Arkansas</OPTION>
			<OPTION VALUE="CA">California</OPTION>
			<OPTION VALUE="CO">Colorado</OPTION>
			<OPTION VALUE="CT">Connecticut</OPTION>
			<OPTION VALUE="DE">Delaware</OPTION>
			<OPTION VALUE="DC">District of Columbia</OPTION>
			<OPTION VALUE="FL">Florida</OPTION>
			<OPTION VALUE="GA">Georgia</OPTION>
			<OPTION VALUE="HI">Hawaii</OPTION>
			<OPTION VALUE="ID">Idaho</OPTION>
			<OPTION VALUE="IL">Illinois</OPTION>
			<OPTION VALUE="IN">Indiana</OPTION>
			<OPTION VALUE="IA">Iowa</OPTION>
			<OPTION VALUE="KS">Kansas</OPTION>
			<OPTION VALUE="KY">Kentucky</OPTION>
			<OPTION VALUE="LA">Louisiana</OPTION>
			<OPTION VALUE="ME">Maine</OPTION>
			<OPTION VALUE="MD">Maryland</OPTION>
			<OPTION VALUE="MA">Massachusetts</OPTION>
			<OPTION VALUE="MI">Michigan</OPTION>
			<OPTION VALUE="MN">Minnesota</OPTION>
			<OPTION VALUE="MS">Mississippi</OPTION>
			<OPTION VALUE="MO">Missouri</OPTION>
			<OPTION VALUE="MY">Montana</OPTION>
			<OPTION VALUE="NE">Nebraska</OPTION>
			<OPTION VALUE="NV">Nevada</OPTION>
			<OPTION VALUE="NH">New Hampshire</OPTION>
			<OPTION VALUE="NJ">New Jersey</OPTION>
			<OPTION VALUE="NM">New Mexico</OPTION>
			<OPTION VALUE="NY">New York</OPTION>
			<OPTION VALUE="NC">North Carolina</OPTION>
			<OPTION VALUE="ND">North Dakota</OPTION>
			<OPTION VALUE="OH">Ohio</OPTION>
			<OPTION VALUE="OK">Oklahoma</OPTION>
			<OPTION VALUE="OR">Oregon</OPTION>
			<OPTION VALUE="PA">Pennsylvania</OPTION>
			<OPTION VALUE="PR">Puerto Rico</OPTION>
			<OPTION VALUE="RI">Rhode Island</OPTION>
			<OPTION VALUE="SC">South Carolina</OPTION>
			<OPTION VALUE="SD">South Dakota</OPTION>
			<OPTION VALUE="TN">Tennessee</OPTION>
			<OPTION VALUE="TX">Texas</OPTION>
			<OPTION VALUE="UT">Utah</OPTION>
			<OPTION VALUE="VT">Vermont</OPTION>
			<OPTION VALUE="VA">Virginia</OPTION>
			<OPTION VALUE="WA">Washington</OPTION>
			<OPTION VALUE="WV">West Virginia</OPTION>
			<OPTION VALUE="WI">Wisconsin</OPTION>
			<OPTION VALUE="WY">Wyoming</OPTION>
			<option VALUE="INT">International</option>
'; */
$StateDropDown = '<option><b>**Select State</b></option>
			<OPTION VALUE="AL">Alabama</OPTION>
			<OPTION VALUE="AK">Alaska</OPTION>
			<OPTION VALUE="AZ">Arizona</OPTION>
			<OPTION VALUE="AR">Arkansas</OPTION>
			<OPTION VALUE="CA">California</OPTION>
			<OPTION VALUE="CO">Colorado</OPTION>
			<OPTION VALUE="CT">Connecticut</OPTION>
			<OPTION VALUE="DE">Delaware</OPTION>
			<OPTION VALUE="DC">District of Columbia</OPTION>
			<OPTION VALUE="FL">Florida</OPTION>
			<OPTION VALUE="GA">Georgia</OPTION>
			<OPTION VALUE="HI">Hawaii</OPTION>
			<OPTION VALUE="ID">Idaho</OPTION>
			<OPTION VALUE="IL">Illinois</OPTION>
			<OPTION VALUE="IN">Indiana</OPTION>
			<OPTION VALUE="IA">Iowa</OPTION>
			<OPTION VALUE="KS">Kansas</OPTION>
			<OPTION VALUE="KY">Kentucky</OPTION>
			<OPTION VALUE="LA">Louisiana</OPTION>
			<OPTION VALUE="ME">Maine</OPTION>
			<OPTION VALUE="MD">Maryland</OPTION>
			<OPTION VALUE="MA">Massachusetts</OPTION>
			<OPTION VALUE="MI">Michigan</OPTION>
			<OPTION VALUE="MN">Minnesota</OPTION>
			<OPTION VALUE="MS">Mississippi</OPTION>
			<OPTION VALUE="MO">Missouri</OPTION>
			<OPTION VALUE="MY">Montana</OPTION>
			<OPTION VALUE="NE">Nebraska</OPTION>
			<OPTION VALUE="NV">Nevada</OPTION>
			<OPTION VALUE="NH">New Hampshire</OPTION>
			<OPTION VALUE="NJ">New Jersey</OPTION>
			<OPTION VALUE="NM">New Mexico</OPTION>
			<OPTION VALUE="NY">New York</OPTION>
			<OPTION VALUE="NC">North Carolina</OPTION>
			<OPTION VALUE="ND">North Dakota</OPTION>
			<OPTION VALUE="OH">Ohio</OPTION>
			<OPTION VALUE="OK">Oklahoma</OPTION>
			<OPTION VALUE="OR">Oregon</OPTION>
			<OPTION VALUE="PA">Pennsylvania</OPTION>
			<OPTION VALUE="PR">Puerto Rico</OPTION>
			<OPTION VALUE="RI">Rhode Island</OPTION>
			<OPTION VALUE="SC">South Carolina</OPTION>
			<OPTION VALUE="SD">South Dakota</OPTION>
			<OPTION VALUE="TN">Tennessee</OPTION>
			<OPTION VALUE="TX">Texas</OPTION>
			<OPTION VALUE="UT">Utah</OPTION>
			<OPTION VALUE="VT">Vermont</OPTION>
			<OPTION VALUE="VA">Virginia</OPTION>
			<OPTION VALUE="WA">Washington</OPTION>
			<OPTION VALUE="WV">West Virginia</OPTION>
			<OPTION VALUE="WI">Wisconsin</OPTION>
			<OPTION VALUE="WY">Wyoming</OPTION>
			<option><b>**Select A Province</b></option>
			<option VALUE="AB">Alberta</OPTION>
			<option VALUE="BC">British Columbia</OPTION>
			<option VALUE="MB">Manitoba</OPTION>
			<option VALUE="NB">New Brunswick</OPTION>
			<option VALUE="NF">Newfoundland</OPTION>
			<option VALUE="NT">Northwest Territories</OPTION>
			<option VALUE="NS">Nova Scotia</OPTION>
			<option VALUE="NU">Nunavut</OPTION>
			<option VALUE="ON">Ontario</OPTION>
			<option VALUE="PE">P.E.I</OPTION>
			<option VALUE="PQ">Quebec</OPTION>
			<option VALUE="SK">Saskatchewan</OPTION>
			<option VALUE="YK">Yukon Territory</OPTION>
			<option VALUE="other">International</option>
'; 
?>