update per_description set name='Content Access' where id= 73;
update per_description set name='Content Edit' where id= 1;
update per_description set name='Content Delete' where id= 2;
update per_description set name='Content Publish' where id= 98;
update per_description set name='Content Section Limit' where id= 97;
update per_description set name='Content Section Delete' where id= 6;
update per_description set name='Content Section Edit' where id= 9;
update per_description set name='Content Class Edit' where id= 8;
update per_description set name='Content Class Delete' where id= 7;
update per_description set name='Content Documents Edit' where id= 85;
update per_description set name='Content Images Edit' where id= 85;
update per_description set name='Content RSS Aggregator' where id= 102;
update per_description set name='Content RSS Publish' where id= 300;
update per_description set name='Content Navigation' where id= 47;
update per_description set name='Content Template' where id= 49;
update per_description set name='Content Css' where id= 48;
update per_description set name='Calendar Access' where id= 11;
update per_description set name='Calendar Publish' where id= 12;
update per_description set name='Calendar Delete' where id= 13;
update per_description set name='FAQ Access' where id= 22;
update per_description set name='FAQ Publish' where id= 24;
update per_description set name='FAQ Delete' where id= 23;
update per_description set name='Links Access' where id= 26;
update per_description set name='Links Publish' where id= 28;
update per_description set name='Links Delete' where id= 27;
update per_description set name='Action Admin' where id= 33;
update per_description set name='Action Access' where id= 31;
update per_description set name='Action Publish' where id= 30;
update per_description set name='Action Delete' where id= 32;
update per_description set name='Gallery Admin' where id= 37;
update per_description set name='Gallery Access' where id= 34;
update per_description set name='Gallery Image Publish' where id= 36;
update per_description set name='Gallery Image Delete' where id= 35;
update per_description set name='Form Admin' where id= 53;
update per_description set name='Form Data Edit' where id= 54;
update per_description set name='Form Data Publish' where id= 55;
update per_description set name='Form Data Email' where id= 301;
update per_description set name='Form Data Export' where id= 302;
update per_description set name='Blast Access' where id= 38;
update per_description set name='Blast Admin' where id= 39;
update per_description set name='Blast Send' where id= 40;
update per_description set name='System Access' where id= 306;
update per_description set name='System Settings' where id= 52;
update per_description set name='System Users' where id= 51;
update per_description set name='System permission' where id= 50;
update per_description set name='Tools Access' where id= 305;
update per_description set name='Tools Admin' where id= 306;
update per_description set name='Tools Introtext' where id= 45;
update per_description set name='Tools Customfiles' where id= 46;
update per_description set name='Contact Admin' where id= 65;
update per_description set name='Contact Campaign' where id= 66;
update per_description set name='Contact Region' where id= 67;
update per_description set name='Contact Type' where id= 68;
update per_description set name='Contact Source' where id= 69;
update per_description set name='Contact User' where id= 70;
update per_description set name='Contact Outlook' where id= 71;
update per_description set name='Contact Access' where id= 72;
update per_description set name='Contact Edit' where id= 95;
update per_description set name='Petition Admin' where id= 74;
update per_description set name='Messages Access' where id= 89;
update per_description set name='Messages Admin' where id= 90;
update per_description set name='Quotes Access' where id= 99;
update per_description set name='Form Media' where id= 18;
update per_description set name='Form Board Ride' where id= 41;
update per_description set name='Form Board Housing' where id= 42;
update per_description set name='Form Groups' where id= 56;
update per_description set name='Form Endorse' where id= 59;
update per_description set name='Form Trainer' where id= 78;
update per_description set name='Form Speaker' where id= 81;
update per_description set name='Form Volunteer' where id= 84;
update per_description set name='Form Petition' where id= 75;
update per_description set name='Payment Access' where id= 303;
update per_description set name='Payment Admin' where id= 304;


replace into per_description ( id, name, publish ) values (305, 'Tools Access', 1);
replace into per_description ( id, name, publish ) values (306, 'Tools Admin', 1);
replace into per_description ( id, name, publish ) values (300,'Content RSS Publish',1);
replace into per_description ( id, name, publish ) values (303, 'Payment Access', 1);
replace into per_description ( id, name, publish ) values (304, 'Payment Admin', 1);
replace into per_description ( id, name, publish ) values (301, 'Form Data Email', 1);
replace into per_description ( id, name, publish ) values (302, 'Form Data Export', 1);

insert into permission (perid, groupid) values (300, 1);
insert into permission (perid, groupid) values (301, 1);
insert into permission (perid, groupid) values (302, 1);
insert into permission (perid, groupid) values (303, 1);
insert into permission (perid, groupid) values (304, 1);
insert into permission (perid, groupid) values (305, 1);
insert into permission (perid, groupid) values (306, 1);
insert into permission (perid, groupid) values (300, 3);
insert into permission (perid, groupid) values (301, 3);
insert into permission (perid, groupid) values (302, 3);
insert into permission (perid, groupid) values (303, 3);
insert into permission (perid, groupid) values (304, 3);
insert into permission (perid, groupid) values (305, 3);
insert into permission (perid, groupid) values (306, 3);
