update per_description set name='Content Access', publish=1 where id= 73;
update per_description set name='Content Edit', publish=1 where id= 1;
update per_description set name='Content Delete', publish=1 where id= 2;
update per_description set name='Content Publish', publish=1 where id= 98;
update per_description set name='Content Section Limit', publish=1 where id= 97;
update per_description set name='Content Section Delete', publish=1 where id= 6;
update per_description set name='Content Section Edit', publish=1 where id= 9;
update per_description set name='Content Class Edit', publish=1 where id= 8;
update per_description set name='Content Class Delete', publish=1 where id= 7;
update per_description set name='Content Images Edit', publish=1 where id= 85;
update per_description set name='Content RSS Aggregator', publish=1 where id= 102;
update per_description set name='Content RSS Publish', publish=1 where id= 300;
update per_description set name='Content Navigation', publish=1 where id= 47;
update per_description set name='Content Template', publish=1 where id= 49;
update per_description set name='Content CSS', publish=1 where id= 48;
update per_description set name='Calendar Access', publish=1 where id= 11;
update per_description set name='Calendar Publish', publish=1 where id= 12;
update per_description set name='Calendar Delete', publish=1 where id= 13;
update per_description set name='FAQ Access', publish=1 where id= 22;
update per_description set name='FAQ Publish', publish=1 where id= 24;
update per_description set name='FAQ Delete', publish=1 where id= 23;
update per_description set name='Links Access', publish=1 where id= 26;
update per_description set name='Links Publish', publish=1 where id= 28;
update per_description set name='Links Delete', publish=1 where id= 27;
update per_description set name='Action Admin', publish=1 where id= 33;
update per_description set name='Action Access', publish=1 where id= 31;
update per_description set name='Action Publish', publish=1 where id= 30;
update per_description set name='Action Delete', publish=1 where id= 32;
update per_description set name='Gallery Admin', publish=1 where id= 37;
update per_description set name='Gallery Access', publish=1 where id= 34;
update per_description set name='Gallery Image Publish', publish=1 where id= 36;
update per_description set name='Gallery Image Delete', publish=1 where id= 35;
update per_description set name='Form Admin', publish=1 where id= 53;
update per_description set name='Form Data Edit', publish=1 where id= 54;
update per_description set name='Form Data Publish', publish=1 where id= 55;
update per_description set name='Form Data Email', publish=1 where id= 301;
update per_description set name='Form Data Export', publish=1 where id= 302;
update per_description set name='Blast Access', publish=1 where id= 38;
update per_description set name='Blast Admin', publish=1 where id= 39;
update per_description set name='Blast Send', publish=1 where id= 40;
update per_description set name='System Access', publish=1 where id= 306;
update per_description set name='System Settings', publish=1 where id= 52;
update per_description set name='System Users', publish=1 where id= 51;
update per_description set name='System Permissions', publish=1 where id= 50;
update per_description set name='Tools Access', publish=1 where id= 305;
update per_description set name='Tools Admin', publish=1 where id= 306;
update per_description set name='Tools Introtext', publish=1 where id= 45;
update per_description set name='Tools Customfiles', publish=1 where id= 46;
update per_description set name='Contact Admin', publish=1 where id= 65;
update per_description set name='Contact Campaign', publish=1 where id= 66;
update per_description set name='Contact Region', publish=1 where id= 67;
update per_description set name='Contact Type', publish=1 where id= 68;
update per_description set name='Contact Source', publish=1 where id= 69;
update per_description set name='Contact User', publish=1 where id= 70;
update per_description set name='Contact Outlook', publish=1 where id= 71;
update per_description set name='Contact Access', publish=1 where id= 72;
update per_description set name='Contact Edit', publish=1 where id= 95;
update per_description set name='Petition Admin', publish=1 where id= 74;
update per_description set name='Messages Access', publish=1 where id= 89;
update per_description set name='Messages Admin', publish=1 where id= 90;
update per_description set name='Quotes Access', publish=1 where id= 99;
update per_description set name='Form Media', publish=1 where id= 18;
update per_description set name='Form Board Ride', publish=1 where id= 41;
update per_description set name='Form Board Housing', publish=1 where id= 42;
update per_description set name='Form Groups', publish=1 where id= 56;
update per_description set name='Form Endorse', publish=1 where id= 59;
update per_description set name='Form Trainer', publish=1 where id= 78;
update per_description set name='Form Speaker', publish=1 where id= 81;
update per_description set name='Form Volunteer', publish=1 where id= 84;
update per_description set name='Form Petition', publish=1 where id= 75;
update per_description set name='Payment Access', publish=1 where id= 303;
update per_description set name='Payment Admin', publish=1 where id= 304;


replace into per_description ( id, name, publish ) values (102, 'RSS Access', 1);
replace into per_description ( id, name, publish ) values (305, 'Tools Access', 1);
replace into per_description ( id, name, publish ) values (306, 'Tools Admin', 1);
replace into per_description ( id, name, publish ) values (300,'Content RSS Publish',1);
replace into per_description ( id, name, publish ) values (303, 'Payment Access', 1);
replace into per_description ( id, name, publish ) values (304, 'Payment Admin', 1);
replace into per_description ( id, name, publish ) values (301, 'Form Data Email', 1);
replace into per_description ( id, name, publish ) values (302, 'Form Data Export', 1);

insert into permission (perid, groupid) values (102, 1);
insert into permission (perid, groupid) values (300, 1);
insert into permission (perid, groupid) values (301, 1);
insert into permission (perid, groupid) values (302, 1);
insert into permission (perid, groupid) values (303, 1);
insert into permission (perid, groupid) values (304, 1);
insert into permission (perid, groupid) values (305, 1);
insert into permission (perid, groupid) values (306, 1);
insert into permission (perid, groupid) values (102, 3);
insert into permission (perid, groupid) values (300, 3);
insert into permission (perid, groupid) values (301, 3);
insert into permission (perid, groupid) values (302, 3);
insert into permission (perid, groupid) values (303, 3);
insert into permission (perid, groupid) values (304, 3);
insert into permission (perid, groupid) values (305, 3);
insert into permission (perid, groupid) values (306, 3);
