alter table userdata_fields change column region_Title lookup_Title varchar(255) null;
alter table userdata_fields change column region_First_Name lookup_First_Name varchar(255) null;
alter table userdata_fields change column region_Last_Name lookup_Last_Name varchar(255) null;
alter table userdata_fields change column region_Suffix lookup_Suffix varchar(255) null;
alter table userdata_fields change column region_MI lookup_MI varchar(255) null;
alter table userdata_fields change column region_Company lookup_Company varchar(255) null;
alter table userdata_fields change column region_Notes lookup_Notes varchar(255) null;
alter table userdata_fields change column region_Email lookup_Email varchar(255) null;
alter table userdata_fields change column region_Phone lookup_Phone varchar(255) null;
alter table userdata_fields change column region_Cell_Phone lookup_Cell_Phone varchar(255) null;
alter table userdata_fields change column region_Phone_Provider lookup_Phone_Provider varchar(255) null;
alter table userdata_fields change column region_Work_Phone lookup_Work_Phone varchar(255) null;
alter table userdata_fields change column region_Pager lookup_Pager varchar(255) null;
alter table userdata_fields change column region_Work_Fax lookup_Work_Fax varchar(255) null;
alter table userdata_fields change column region_Home_Fax lookup_Home_Fax varchar(255) null;
alter table userdata_fields change column region_Web_Page lookup_Web_Page varchar(255) null;
alter table userdata_fields change column region_Street lookup_Street varchar(255) null;
alter table userdata_fields change column region_Street_2 lookup_Street_2 varchar(255) null;
alter table userdata_fields change column region_Street_3 lookup_Street_3 varchar(255) null;
alter table userdata_fields change column region_City lookup_City varchar(255) null;
alter table userdata_fields change column region_State lookup_State varchar(255) null;
alter table userdata_fields change column region_Zip lookup_Zip varchar(255) null;
alter table userdata_fields change column region_Country lookup_Country varchar(255) null;
alter table userdata_fields change column region_occupation lookup_occupation varchar(255) null;
alter table userdata_fields change column region_region lookup_region varchar(255) null;
alter table userdata_fields change column region_custom1 lookup_custom1 varchar(255) null;
alter table userdata_fields change column region_custom2 lookup_custom2 varchar(255) null;
alter table userdata_fields change column region_custom3 lookup_custom3 varchar(255) null;
alter table userdata_fields change column region_custom4 lookup_custom4 varchar(255) null;
alter table userdata_fields change column region_custom5 lookup_custom5 varchar(255) null;
alter table userdata_fields change column region_custom6 lookup_custom6 varchar(255) null;
alter table userdata_fields change column region_custom7 lookup_custom7 varchar(255) null;
alter table userdata_fields change column region_custom8 lookup_custom8 varchar(255) null;
alter table userdata_fields change column region_custom9 lookup_custom9 varchar(255) null;
alter table userdata_fields change column region_custom10 lookup_custom10 varchar(255) null;
alter table userdata_fields change column region_custom11 lookup_custom11 varchar(255) null;
alter table userdata_fields change column region_custom12 lookup_custom12 varchar(255) null;
alter table userdata_fields change column region_custom13 lookup_custom13 varchar(255) null;
alter table userdata_fields change column region_custom14 lookup_custom14 varchar(255) null;
alter table userdata_fields change column region_custom15 lookup_custom15 varchar(255) null;
alter table userdata_fields change column region_custom16 lookup_custom16 varchar(255) null;
alter table userdata_fields change column region_custom17 lookup_custom17 varchar(255) null;
alter table userdata_fields change column region_custom18 lookup_custom18 varchar(255) null;
alter table userdata_fields change column region_custom19 lookup_custom19 varchar(255) null;
alter table userdata_fields change column region_custom20 lookup_custom20 varchar(255) null;
alter table userdata_fields change column region_custom21 lookup_custom21 varchar(255) null;
alter table userdata_fields change column region_custom22 lookup_custom22 varchar(255) null;
alter table userdata_fields change column region_custom23 lookup_custom23 varchar(255) null;
alter table userdata_fields change column region_custom24 lookup_custom24 varchar(255) null;
alter table userdata_fields change column region_custom25 lookup_custom25 varchar(255) null;
alter table userdata_fields change column region_custom26 lookup_custom26 varchar(255) null;
alter table userdata_fields change column region_custom27 lookup_custom27 varchar(255) null;
alter table userdata_fields change column region_custom28 lookup_custom28 varchar(255) null;
alter table userdata_fields change column region_custom29 lookup_custom29 varchar(255) null;
alter table userdata_fields change column region_custom30 lookup_custom30 varchar(255) null;
alter table userdata_fields change column region_custom31 lookup_custom31 varchar(255) null;
alter table userdata_fields change column region_custom32 lookup_custom32 varchar(255) null;
alter table userdata_fields change column region_custom33 lookup_custom33 varchar(255) null;
alter table userdata_fields change column region_custom34 lookup_custom34 varchar(255) null;
alter table userdata_fields change column region_custom35 lookup_custom35 varchar(255) null;
alter table userdata_fields change column region_custom36 lookup_custom36 varchar(255) null;
alter table userdata_fields change column region_custom37 lookup_custom37 varchar(255) null;
alter table userdata_fields change column region_custom38 lookup_custom38 varchar(255) null;
alter table userdata_fields change column region_custom39 lookup_custom39 varchar(255) null;
alter table userdata_fields change column region_custom40 lookup_custom40 varchar(255) null;
update userdata_fields set lookup_Title = 'AMPSystemLookup_Regions_US' where lookup_Title = 'US';
update userdata_fields set lookup_Title = 'AMPSystemLookup_Regions_Canada' where lookup_Title = 'CDN';
update userdata_fields set lookup_Title = 'AMPSystemLookup_Regions_World_Long' where lookup_Title = 'WORLD-LONG';
update userdata_fields set lookup_Title = 'AMPSystemLookup_Regions_World' where lookup_Title = 'WORLD';
update userdata_fields set lookup_Title = 'AMPSystemLookup_Regions_US_and_Canada' where lookup_Title = 'US AND CANADA';
update userdata_fields set lookup_First_Name = 'AMPSystemLookup_Regions_US' where lookup_First_Name = 'US';
update userdata_fields set lookup_First_Name = 'AMPSystemLookup_Regions_Canada' where lookup_First_Name = 'CDN';
update userdata_fields set lookup_First_Name = 'AMPSystemLookup_Regions_World_Long' where lookup_First_Name = 'WORLD-LONG';
update userdata_fields set lookup_First_Name = 'AMPSystemLookup_Regions_World' where lookup_First_Name = 'WORLD';
update userdata_fields set lookup_First_Name = 'AMPSystemLookup_Regions_US_and_Canada' where lookup_First_Name = 'US AND CANADA';
update userdata_fields set lookup_Last_Name = 'AMPSystemLookup_Regions_US' where lookup_Last_Name = 'US';
update userdata_fields set lookup_Last_Name = 'AMPSystemLookup_Regions_Canada' where lookup_Last_Name = 'CDN';
update userdata_fields set lookup_Last_Name = 'AMPSystemLookup_Regions_World_Long' where lookup_Last_Name = 'WORLD-LONG';
update userdata_fields set lookup_Last_Name = 'AMPSystemLookup_Regions_World' where lookup_Last_Name = 'WORLD';
update userdata_fields set lookup_Last_Name = 'AMPSystemLookup_Regions_US_and_Canada' where lookup_Last_Name = 'US AND CANADA';
update userdata_fields set lookup_Suffix = 'AMPSystemLookup_Regions_US' where lookup_Suffix = 'US';
update userdata_fields set lookup_Suffix = 'AMPSystemLookup_Regions_Canada' where lookup_Suffix = 'CDN';
update userdata_fields set lookup_Suffix = 'AMPSystemLookup_Regions_World_Long' where lookup_Suffix = 'WORLD-LONG';
update userdata_fields set lookup_Suffix = 'AMPSystemLookup_Regions_World' where lookup_Suffix = 'WORLD';
update userdata_fields set lookup_Suffix = 'AMPSystemLookup_Regions_US_and_Canada' where lookup_Suffix = 'US AND CANADA';
update userdata_fields set lookup_MI = 'AMPSystemLookup_Regions_US' where lookup_MI = 'US';
update userdata_fields set lookup_MI = 'AMPSystemLookup_Regions_Canada' where lookup_MI = 'CDN';
update userdata_fields set lookup_MI = 'AMPSystemLookup_Regions_World_Long' where lookup_MI = 'WORLD-LONG';
update userdata_fields set lookup_MI = 'AMPSystemLookup_Regions_World' where lookup_MI = 'WORLD';
update userdata_fields set lookup_MI = 'AMPSystemLookup_Regions_US_and_Canada' where lookup_MI = 'US AND CANADA';
update userdata_fields set lookup_Company = 'AMPSystemLookup_Regions_US' where lookup_Company = 'US';
update userdata_fields set lookup_Company = 'AMPSystemLookup_Regions_Canada' where lookup_Company = 'CDN';
update userdata_fields set lookup_Company = 'AMPSystemLookup_Regions_World_Long' where lookup_Company = 'WORLD-LONG';
update userdata_fields set lookup_Company = 'AMPSystemLookup_Regions_World' where lookup_Company = 'WORLD';
update userdata_fields set lookup_Company = 'AMPSystemLookup_Regions_US_and_Canada' where lookup_Company = 'US AND CANADA';
update userdata_fields set lookup_Notes = 'AMPSystemLookup_Regions_US' where lookup_Notes = 'US';
update userdata_fields set lookup_Notes = 'AMPSystemLookup_Regions_Canada' where lookup_Notes = 'CDN';
update userdata_fields set lookup_Notes = 'AMPSystemLookup_Regions_World_Long' where lookup_Notes = 'WORLD-LONG';
update userdata_fields set lookup_Notes = 'AMPSystemLookup_Regions_World' where lookup_Notes = 'WORLD';
update userdata_fields set lookup_Notes = 'AMPSystemLookup_Regions_US_and_Canada' where lookup_Notes = 'US AND CANADA';
update userdata_fields set lookup_Email = 'AMPSystemLookup_Regions_US' where lookup_Email = 'US';
update userdata_fields set lookup_Email = 'AMPSystemLookup_Regions_Canada' where lookup_Email = 'CDN';
update userdata_fields set lookup_Email = 'AMPSystemLookup_Regions_World_Long' where lookup_Email = 'WORLD-LONG';
update userdata_fields set lookup_Email = 'AMPSystemLookup_Regions_World' where lookup_Email = 'WORLD';
update userdata_fields set lookup_Email = 'AMPSystemLookup_Regions_US_and_Canada' where lookup_Email = 'US AND CANADA';
update userdata_fields set lookup_Phone = 'AMPSystemLookup_Regions_US' where lookup_Phone = 'US';
update userdata_fields set lookup_Phone = 'AMPSystemLookup_Regions_Canada' where lookup_Phone = 'CDN';
update userdata_fields set lookup_Phone = 'AMPSystemLookup_Regions_World_Long' where lookup_Phone = 'WORLD-LONG';
update userdata_fields set lookup_Phone = 'AMPSystemLookup_Regions_World' where lookup_Phone = 'WORLD';
update userdata_fields set lookup_Phone = 'AMPSystemLookup_Regions_US_and_Canada' where lookup_Phone = 'US AND CANADA';
update userdata_fields set lookup_Cell_Phone = 'AMPSystemLookup_Regions_US' where lookup_Cell_Phone = 'US';
update userdata_fields set lookup_Cell_Phone = 'AMPSystemLookup_Regions_Canada' where lookup_Cell_Phone = 'CDN';
update userdata_fields set lookup_Cell_Phone = 'AMPSystemLookup_Regions_World_Long' where lookup_Cell_Phone = 'WORLD-LONG';
update userdata_fields set lookup_Cell_Phone = 'AMPSystemLookup_Regions_World' where lookup_Cell_Phone = 'WORLD';
update userdata_fields set lookup_Cell_Phone = 'AMPSystemLookup_Regions_US_and_Canada' where lookup_Cell_Phone = 'US AND CANADA';
update userdata_fields set lookup_Phone_Provider = 'AMPSystemLookup_Regions_US' where lookup_Phone_Provider = 'US';
update userdata_fields set lookup_Phone_Provider = 'AMPSystemLookup_Regions_Canada' where lookup_Phone_Provider = 'CDN';
update userdata_fields set lookup_Phone_Provider = 'AMPSystemLookup_Regions_World_Long' where lookup_Phone_Provider = 'WORLD-LONG';
update userdata_fields set lookup_Phone_Provider = 'AMPSystemLookup_Regions_World' where lookup_Phone_Provider = 'WORLD';
update userdata_fields set lookup_Phone_Provider = 'AMPSystemLookup_Regions_US_and_Canada' where lookup_Phone_Provider = 'US AND CANADA';
update userdata_fields set lookup_Work_Phone = 'AMPSystemLookup_Regions_US' where lookup_Work_Phone = 'US';
update userdata_fields set lookup_Work_Phone = 'AMPSystemLookup_Regions_Canada' where lookup_Work_Phone = 'CDN';
update userdata_fields set lookup_Work_Phone = 'AMPSystemLookup_Regions_World_Long' where lookup_Work_Phone = 'WORLD-LONG';
update userdata_fields set lookup_Work_Phone = 'AMPSystemLookup_Regions_World' where lookup_Work_Phone = 'WORLD';
update userdata_fields set lookup_Work_Phone = 'AMPSystemLookup_Regions_US_and_Canada' where lookup_Work_Phone = 'US AND CANADA';
update userdata_fields set lookup_Pager = 'AMPSystemLookup_Regions_US' where lookup_Pager = 'US';
update userdata_fields set lookup_Pager = 'AMPSystemLookup_Regions_Canada' where lookup_Pager = 'CDN';
update userdata_fields set lookup_Pager = 'AMPSystemLookup_Regions_World_Long' where lookup_Pager = 'WORLD-LONG';
update userdata_fields set lookup_Pager = 'AMPSystemLookup_Regions_World' where lookup_Pager = 'WORLD';
update userdata_fields set lookup_Pager = 'AMPSystemLookup_Regions_US_and_Canada' where lookup_Pager = 'US AND CANADA';
update userdata_fields set lookup_Work_Fax = 'AMPSystemLookup_Regions_US' where lookup_Work_Fax = 'US';
update userdata_fields set lookup_Work_Fax = 'AMPSystemLookup_Regions_Canada' where lookup_Work_Fax = 'CDN';
update userdata_fields set lookup_Work_Fax = 'AMPSystemLookup_Regions_World_Long' where lookup_Work_Fax = 'WORLD-LONG';
update userdata_fields set lookup_Work_Fax = 'AMPSystemLookup_Regions_World' where lookup_Work_Fax = 'WORLD';
update userdata_fields set lookup_Work_Fax = 'AMPSystemLookup_Regions_US_and_Canada' where lookup_Work_Fax = 'US AND CANADA';
update userdata_fields set lookup_Home_Fax = 'AMPSystemLookup_Regions_US' where lookup_Home_Fax = 'US';
update userdata_fields set lookup_Home_Fax = 'AMPSystemLookup_Regions_Canada' where lookup_Home_Fax = 'CDN';
update userdata_fields set lookup_Home_Fax = 'AMPSystemLookup_Regions_World_Long' where lookup_Home_Fax = 'WORLD-LONG';
update userdata_fields set lookup_Home_Fax = 'AMPSystemLookup_Regions_World' where lookup_Home_Fax = 'WORLD';
update userdata_fields set lookup_Home_Fax = 'AMPSystemLookup_Regions_US_and_Canada' where lookup_Home_Fax = 'US AND CANADA';
update userdata_fields set lookup_Web_Page = 'AMPSystemLookup_Regions_US' where lookup_Web_Page = 'US';
update userdata_fields set lookup_Web_Page = 'AMPSystemLookup_Regions_Canada' where lookup_Web_Page = 'CDN';
update userdata_fields set lookup_Web_Page = 'AMPSystemLookup_Regions_World_Long' where lookup_Web_Page = 'WORLD-LONG';
update userdata_fields set lookup_Web_Page = 'AMPSystemLookup_Regions_World' where lookup_Web_Page = 'WORLD';
update userdata_fields set lookup_Web_Page = 'AMPSystemLookup_Regions_US_and_Canada' where lookup_Web_Page = 'US AND CANADA';
update userdata_fields set lookup_Street = 'AMPSystemLookup_Regions_US' where lookup_Street = 'US';
update userdata_fields set lookup_Street = 'AMPSystemLookup_Regions_Canada' where lookup_Street = 'CDN';
update userdata_fields set lookup_Street = 'AMPSystemLookup_Regions_World_Long' where lookup_Street = 'WORLD-LONG';
update userdata_fields set lookup_Street = 'AMPSystemLookup_Regions_World' where lookup_Street = 'WORLD';
update userdata_fields set lookup_Street = 'AMPSystemLookup_Regions_US_and_Canada' where lookup_Street = 'US AND CANADA';
update userdata_fields set lookup_Street_2 = 'AMPSystemLookup_Regions_US' where lookup_Street_2 = 'US';
update userdata_fields set lookup_Street_2 = 'AMPSystemLookup_Regions_Canada' where lookup_Street_2 = 'CDN';
update userdata_fields set lookup_Street_2 = 'AMPSystemLookup_Regions_World_Long' where lookup_Street_2 = 'WORLD-LONG';
update userdata_fields set lookup_Street_2 = 'AMPSystemLookup_Regions_World' where lookup_Street_2 = 'WORLD';
update userdata_fields set lookup_Street_2 = 'AMPSystemLookup_Regions_US_and_Canada' where lookup_Street_2 = 'US AND CANADA';
update userdata_fields set lookup_Street_3 = 'AMPSystemLookup_Regions_US' where lookup_Street_3 = 'US';
update userdata_fields set lookup_Street_3 = 'AMPSystemLookup_Regions_Canada' where lookup_Street_3 = 'CDN';
update userdata_fields set lookup_Street_3 = 'AMPSystemLookup_Regions_World_Long' where lookup_Street_3 = 'WORLD-LONG';
update userdata_fields set lookup_Street_3 = 'AMPSystemLookup_Regions_World' where lookup_Street_3 = 'WORLD';
update userdata_fields set lookup_Street_3 = 'AMPSystemLookup_Regions_US_and_Canada' where lookup_Street_3 = 'US AND CANADA';
update userdata_fields set lookup_City = 'AMPSystemLookup_Regions_US' where lookup_City = 'US';
update userdata_fields set lookup_City = 'AMPSystemLookup_Regions_Canada' where lookup_City = 'CDN';
update userdata_fields set lookup_City = 'AMPSystemLookup_Regions_World_Long' where lookup_City = 'WORLD-LONG';
update userdata_fields set lookup_City = 'AMPSystemLookup_Regions_World' where lookup_City = 'WORLD';
update userdata_fields set lookup_City = 'AMPSystemLookup_Regions_US_and_Canada' where lookup_City = 'US AND CANADA';
update userdata_fields set lookup_State = 'AMPSystemLookup_Regions_US' where lookup_State = 'US';
update userdata_fields set lookup_State = 'AMPSystemLookup_Regions_Canada' where lookup_State = 'CDN';
update userdata_fields set lookup_State = 'AMPSystemLookup_Regions_World_Long' where lookup_State = 'WORLD-LONG';
update userdata_fields set lookup_State = 'AMPSystemLookup_Regions_World' where lookup_State = 'WORLD';
update userdata_fields set lookup_State = 'AMPSystemLookup_Regions_US_and_Canada' where lookup_State = 'US AND CANADA';
update userdata_fields set lookup_Zip = 'AMPSystemLookup_Regions_US' where lookup_Zip = 'US';
update userdata_fields set lookup_Zip = 'AMPSystemLookup_Regions_Canada' where lookup_Zip = 'CDN';
update userdata_fields set lookup_Zip = 'AMPSystemLookup_Regions_World_Long' where lookup_Zip = 'WORLD-LONG';
update userdata_fields set lookup_Zip = 'AMPSystemLookup_Regions_World' where lookup_Zip = 'WORLD';
update userdata_fields set lookup_Zip = 'AMPSystemLookup_Regions_US_and_Canada' where lookup_Zip = 'US AND CANADA';
update userdata_fields set lookup_Country = 'AMPSystemLookup_Regions_US' where lookup_Country = 'US';
update userdata_fields set lookup_Country = 'AMPSystemLookup_Regions_Canada' where lookup_Country = 'CDN';
update userdata_fields set lookup_Country = 'AMPSystemLookup_Regions_World_Long' where lookup_Country = 'WORLD-LONG';
update userdata_fields set lookup_Country = 'AMPSystemLookup_Regions_World' where lookup_Country = 'WORLD';
update userdata_fields set lookup_Country = 'AMPSystemLookup_Regions_US_and_Canada' where lookup_Country = 'US AND CANADA';
update userdata_fields set lookup_occupation = 'AMPSystemLookup_Regions_US' where lookup_occupation = 'US';
update userdata_fields set lookup_occupation = 'AMPSystemLookup_Regions_Canada' where lookup_occupation = 'CDN';
update userdata_fields set lookup_occupation = 'AMPSystemLookup_Regions_World_Long' where lookup_occupation = 'WORLD-LONG';
update userdata_fields set lookup_occupation = 'AMPSystemLookup_Regions_World' where lookup_occupation = 'WORLD';
update userdata_fields set lookup_occupation = 'AMPSystemLookup_Regions_US_and_Canada' where lookup_occupation = 'US AND CANADA';
update userdata_fields set lookup_region = 'AMPSystemLookup_Regions_US' where lookup_region = 'US';
update userdata_fields set lookup_region = 'AMPSystemLookup_Regions_Canada' where lookup_region = 'CDN';
update userdata_fields set lookup_region = 'AMPSystemLookup_Regions_World_Long' where lookup_region = 'WORLD-LONG';
update userdata_fields set lookup_region = 'AMPSystemLookup_Regions_World' where lookup_region = 'WORLD';
update userdata_fields set lookup_region = 'AMPSystemLookup_Regions_US_and_Canada' where lookup_region = 'US AND CANADA';
update userdata_fields set lookup_custom1 = 'AMPSystemLookup_Regions_US' where lookup_custom1 = 'US';
update userdata_fields set lookup_custom1 = 'AMPSystemLookup_Regions_Canada' where lookup_custom1 = 'CDN';
update userdata_fields set lookup_custom1 = 'AMPSystemLookup_Regions_World_Long' where lookup_custom1 = 'WORLD-LONG';
update userdata_fields set lookup_custom1 = 'AMPSystemLookup_Regions_World' where lookup_custom1 = 'WORLD';
update userdata_fields set lookup_custom1 = 'AMPSystemLookup_Regions_US_and_Canada' where lookup_custom1 = 'US AND CANADA';
update userdata_fields set lookup_custom2 = 'AMPSystemLookup_Regions_US' where lookup_custom2 = 'US';
update userdata_fields set lookup_custom2 = 'AMPSystemLookup_Regions_Canada' where lookup_custom2 = 'CDN';
update userdata_fields set lookup_custom2 = 'AMPSystemLookup_Regions_World_Long' where lookup_custom2 = 'WORLD-LONG';
update userdata_fields set lookup_custom2 = 'AMPSystemLookup_Regions_World' where lookup_custom2 = 'WORLD';
update userdata_fields set lookup_custom2 = 'AMPSystemLookup_Regions_US_and_Canada' where lookup_custom2 = 'US AND CANADA';
update userdata_fields set lookup_custom3 = 'AMPSystemLookup_Regions_US' where lookup_custom3 = 'US';
update userdata_fields set lookup_custom3 = 'AMPSystemLookup_Regions_Canada' where lookup_custom3 = 'CDN';
update userdata_fields set lookup_custom3 = 'AMPSystemLookup_Regions_World_Long' where lookup_custom3 = 'WORLD-LONG';
update userdata_fields set lookup_custom3 = 'AMPSystemLookup_Regions_World' where lookup_custom3 = 'WORLD';
update userdata_fields set lookup_custom3 = 'AMPSystemLookup_Regions_US_and_Canada' where lookup_custom3 = 'US AND CANADA';
update userdata_fields set lookup_custom4 = 'AMPSystemLookup_Regions_US' where lookup_custom4 = 'US';
update userdata_fields set lookup_custom4 = 'AMPSystemLookup_Regions_Canada' where lookup_custom4 = 'CDN';
update userdata_fields set lookup_custom4 = 'AMPSystemLookup_Regions_World_Long' where lookup_custom4 = 'WORLD-LONG';
update userdata_fields set lookup_custom4 = 'AMPSystemLookup_Regions_World' where lookup_custom4 = 'WORLD';
update userdata_fields set lookup_custom4 = 'AMPSystemLookup_Regions_US_and_Canada' where lookup_custom4 = 'US AND CANADA';
update userdata_fields set lookup_custom5 = 'AMPSystemLookup_Regions_US' where lookup_custom5 = 'US';
update userdata_fields set lookup_custom5 = 'AMPSystemLookup_Regions_Canada' where lookup_custom5 = 'CDN';
update userdata_fields set lookup_custom5 = 'AMPSystemLookup_Regions_World_Long' where lookup_custom5 = 'WORLD-LONG';
update userdata_fields set lookup_custom5 = 'AMPSystemLookup_Regions_World' where lookup_custom5 = 'WORLD';
update userdata_fields set lookup_custom5 = 'AMPSystemLookup_Regions_US_and_Canada' where lookup_custom5 = 'US AND CANADA';
update userdata_fields set lookup_custom6 = 'AMPSystemLookup_Regions_US' where lookup_custom6 = 'US';
update userdata_fields set lookup_custom6 = 'AMPSystemLookup_Regions_Canada' where lookup_custom6 = 'CDN';
update userdata_fields set lookup_custom6 = 'AMPSystemLookup_Regions_World_Long' where lookup_custom6 = 'WORLD-LONG';
update userdata_fields set lookup_custom6 = 'AMPSystemLookup_Regions_World' where lookup_custom6 = 'WORLD';
update userdata_fields set lookup_custom6 = 'AMPSystemLookup_Regions_US_and_Canada' where lookup_custom6 = 'US AND CANADA';
update userdata_fields set lookup_custom7 = 'AMPSystemLookup_Regions_US' where lookup_custom7 = 'US';
update userdata_fields set lookup_custom7 = 'AMPSystemLookup_Regions_Canada' where lookup_custom7 = 'CDN';
update userdata_fields set lookup_custom7 = 'AMPSystemLookup_Regions_World_Long' where lookup_custom7 = 'WORLD-LONG';
update userdata_fields set lookup_custom7 = 'AMPSystemLookup_Regions_World' where lookup_custom7 = 'WORLD';
update userdata_fields set lookup_custom7 = 'AMPSystemLookup_Regions_US_and_Canada' where lookup_custom7 = 'US AND CANADA';
update userdata_fields set lookup_custom8 = 'AMPSystemLookup_Regions_US' where lookup_custom8 = 'US';
update userdata_fields set lookup_custom8 = 'AMPSystemLookup_Regions_Canada' where lookup_custom8 = 'CDN';
update userdata_fields set lookup_custom8 = 'AMPSystemLookup_Regions_World_Long' where lookup_custom8 = 'WORLD-LONG';
update userdata_fields set lookup_custom8 = 'AMPSystemLookup_Regions_World' where lookup_custom8 = 'WORLD';
update userdata_fields set lookup_custom8 = 'AMPSystemLookup_Regions_US_and_Canada' where lookup_custom8 = 'US AND CANADA';
update userdata_fields set lookup_custom9 = 'AMPSystemLookup_Regions_US' where lookup_custom9 = 'US';
update userdata_fields set lookup_custom9 = 'AMPSystemLookup_Regions_Canada' where lookup_custom9 = 'CDN';
update userdata_fields set lookup_custom9 = 'AMPSystemLookup_Regions_World_Long' where lookup_custom9 = 'WORLD-LONG';
update userdata_fields set lookup_custom9 = 'AMPSystemLookup_Regions_World' where lookup_custom9 = 'WORLD';
update userdata_fields set lookup_custom9 = 'AMPSystemLookup_Regions_US_and_Canada' where lookup_custom9 = 'US AND CANADA';
update userdata_fields set lookup_custom10 = 'AMPSystemLookup_Regions_US' where lookup_custom10 = 'US';
update userdata_fields set lookup_custom10 = 'AMPSystemLookup_Regions_Canada' where lookup_custom10 = 'CDN';
update userdata_fields set lookup_custom10 = 'AMPSystemLookup_Regions_World_Long' where lookup_custom10 = 'WORLD-LONG';
update userdata_fields set lookup_custom10 = 'AMPSystemLookup_Regions_World' where lookup_custom10 = 'WORLD';
update userdata_fields set lookup_custom10 = 'AMPSystemLookup_Regions_US_and_Canada' where lookup_custom10 = 'US AND CANADA';
update userdata_fields set lookup_custom11 = 'AMPSystemLookup_Regions_US' where lookup_custom11 = 'US';
update userdata_fields set lookup_custom11 = 'AMPSystemLookup_Regions_Canada' where lookup_custom11 = 'CDN';
update userdata_fields set lookup_custom11 = 'AMPSystemLookup_Regions_World_Long' where lookup_custom11 = 'WORLD-LONG';
update userdata_fields set lookup_custom11 = 'AMPSystemLookup_Regions_World' where lookup_custom11 = 'WORLD';
update userdata_fields set lookup_custom11 = 'AMPSystemLookup_Regions_US_and_Canada' where lookup_custom11 = 'US AND CANADA';
update userdata_fields set lookup_custom12 = 'AMPSystemLookup_Regions_US' where lookup_custom12 = 'US';
update userdata_fields set lookup_custom12 = 'AMPSystemLookup_Regions_Canada' where lookup_custom12 = 'CDN';
update userdata_fields set lookup_custom12 = 'AMPSystemLookup_Regions_World_Long' where lookup_custom12 = 'WORLD-LONG';
update userdata_fields set lookup_custom12 = 'AMPSystemLookup_Regions_World' where lookup_custom12 = 'WORLD';
update userdata_fields set lookup_custom12 = 'AMPSystemLookup_Regions_US_and_Canada' where lookup_custom12 = 'US AND CANADA';
update userdata_fields set lookup_custom13 = 'AMPSystemLookup_Regions_US' where lookup_custom13 = 'US';
update userdata_fields set lookup_custom13 = 'AMPSystemLookup_Regions_Canada' where lookup_custom13 = 'CDN';
update userdata_fields set lookup_custom13 = 'AMPSystemLookup_Regions_World_Long' where lookup_custom13 = 'WORLD-LONG';
update userdata_fields set lookup_custom13 = 'AMPSystemLookup_Regions_World' where lookup_custom13 = 'WORLD';
update userdata_fields set lookup_custom13 = 'AMPSystemLookup_Regions_US_and_Canada' where lookup_custom13 = 'US AND CANADA';
update userdata_fields set lookup_custom14 = 'AMPSystemLookup_Regions_US' where lookup_custom14 = 'US';
update userdata_fields set lookup_custom14 = 'AMPSystemLookup_Regions_Canada' where lookup_custom14 = 'CDN';
update userdata_fields set lookup_custom14 = 'AMPSystemLookup_Regions_World_Long' where lookup_custom14 = 'WORLD-LONG';
update userdata_fields set lookup_custom14 = 'AMPSystemLookup_Regions_World' where lookup_custom14 = 'WORLD';
update userdata_fields set lookup_custom14 = 'AMPSystemLookup_Regions_US_and_Canada' where lookup_custom14 = 'US AND CANADA';
update userdata_fields set lookup_custom15 = 'AMPSystemLookup_Regions_US' where lookup_custom15 = 'US';
update userdata_fields set lookup_custom15 = 'AMPSystemLookup_Regions_Canada' where lookup_custom15 = 'CDN';
update userdata_fields set lookup_custom15 = 'AMPSystemLookup_Regions_World_Long' where lookup_custom15 = 'WORLD-LONG';
update userdata_fields set lookup_custom15 = 'AMPSystemLookup_Regions_World' where lookup_custom15 = 'WORLD';
update userdata_fields set lookup_custom15 = 'AMPSystemLookup_Regions_US_and_Canada' where lookup_custom15 = 'US AND CANADA';
update userdata_fields set lookup_custom16 = 'AMPSystemLookup_Regions_US' where lookup_custom16 = 'US';
update userdata_fields set lookup_custom16 = 'AMPSystemLookup_Regions_Canada' where lookup_custom16 = 'CDN';
update userdata_fields set lookup_custom16 = 'AMPSystemLookup_Regions_World_Long' where lookup_custom16 = 'WORLD-LONG';
update userdata_fields set lookup_custom16 = 'AMPSystemLookup_Regions_World' where lookup_custom16 = 'WORLD';
update userdata_fields set lookup_custom16 = 'AMPSystemLookup_Regions_US_and_Canada' where lookup_custom16 = 'US AND CANADA';
update userdata_fields set lookup_custom17 = 'AMPSystemLookup_Regions_US' where lookup_custom17 = 'US';
update userdata_fields set lookup_custom17 = 'AMPSystemLookup_Regions_Canada' where lookup_custom17 = 'CDN';
update userdata_fields set lookup_custom17 = 'AMPSystemLookup_Regions_World_Long' where lookup_custom17 = 'WORLD-LONG';
update userdata_fields set lookup_custom17 = 'AMPSystemLookup_Regions_World' where lookup_custom17 = 'WORLD';
update userdata_fields set lookup_custom17 = 'AMPSystemLookup_Regions_US_and_Canada' where lookup_custom17 = 'US AND CANADA';
update userdata_fields set lookup_custom18 = 'AMPSystemLookup_Regions_US' where lookup_custom18 = 'US';
update userdata_fields set lookup_custom18 = 'AMPSystemLookup_Regions_Canada' where lookup_custom18 = 'CDN';
update userdata_fields set lookup_custom18 = 'AMPSystemLookup_Regions_World_Long' where lookup_custom18 = 'WORLD-LONG';
update userdata_fields set lookup_custom18 = 'AMPSystemLookup_Regions_World' where lookup_custom18 = 'WORLD';
update userdata_fields set lookup_custom18 = 'AMPSystemLookup_Regions_US_and_Canada' where lookup_custom18 = 'US AND CANADA';
update userdata_fields set lookup_custom19 = 'AMPSystemLookup_Regions_US' where lookup_custom19 = 'US';
update userdata_fields set lookup_custom19 = 'AMPSystemLookup_Regions_Canada' where lookup_custom19 = 'CDN';
update userdata_fields set lookup_custom19 = 'AMPSystemLookup_Regions_World_Long' where lookup_custom19 = 'WORLD-LONG';
update userdata_fields set lookup_custom19 = 'AMPSystemLookup_Regions_World' where lookup_custom19 = 'WORLD';
update userdata_fields set lookup_custom19 = 'AMPSystemLookup_Regions_US_and_Canada' where lookup_custom19 = 'US AND CANADA';
update userdata_fields set lookup_custom20 = 'AMPSystemLookup_Regions_US' where lookup_custom20 = 'US';
update userdata_fields set lookup_custom20 = 'AMPSystemLookup_Regions_Canada' where lookup_custom20 = 'CDN';
update userdata_fields set lookup_custom20 = 'AMPSystemLookup_Regions_World_Long' where lookup_custom20 = 'WORLD-LONG';
update userdata_fields set lookup_custom20 = 'AMPSystemLookup_Regions_World' where lookup_custom20 = 'WORLD';
update userdata_fields set lookup_custom20 = 'AMPSystemLookup_Regions_US_and_Canada' where lookup_custom20 = 'US AND CANADA';
update userdata_fields set lookup_custom21 = 'AMPSystemLookup_Regions_US' where lookup_custom21 = 'US';
update userdata_fields set lookup_custom21 = 'AMPSystemLookup_Regions_Canada' where lookup_custom21 = 'CDN';
update userdata_fields set lookup_custom21 = 'AMPSystemLookup_Regions_World_Long' where lookup_custom21 = 'WORLD-LONG';
update userdata_fields set lookup_custom21 = 'AMPSystemLookup_Regions_World' where lookup_custom21 = 'WORLD';
update userdata_fields set lookup_custom21 = 'AMPSystemLookup_Regions_US_and_Canada' where lookup_custom21 = 'US AND CANADA';
update userdata_fields set lookup_custom22 = 'AMPSystemLookup_Regions_US' where lookup_custom22 = 'US';
update userdata_fields set lookup_custom22 = 'AMPSystemLookup_Regions_Canada' where lookup_custom22 = 'CDN';
update userdata_fields set lookup_custom22 = 'AMPSystemLookup_Regions_World_Long' where lookup_custom22 = 'WORLD-LONG';
update userdata_fields set lookup_custom22 = 'AMPSystemLookup_Regions_World' where lookup_custom22 = 'WORLD';
update userdata_fields set lookup_custom22 = 'AMPSystemLookup_Regions_US_and_Canada' where lookup_custom22 = 'US AND CANADA';
update userdata_fields set lookup_custom23 = 'AMPSystemLookup_Regions_US' where lookup_custom23 = 'US';
update userdata_fields set lookup_custom23 = 'AMPSystemLookup_Regions_Canada' where lookup_custom23 = 'CDN';
update userdata_fields set lookup_custom23 = 'AMPSystemLookup_Regions_World_Long' where lookup_custom23 = 'WORLD-LONG';
update userdata_fields set lookup_custom23 = 'AMPSystemLookup_Regions_World' where lookup_custom23 = 'WORLD';
update userdata_fields set lookup_custom23 = 'AMPSystemLookup_Regions_US_and_Canada' where lookup_custom23 = 'US AND CANADA';
update userdata_fields set lookup_custom24 = 'AMPSystemLookup_Regions_US' where lookup_custom24 = 'US';
update userdata_fields set lookup_custom24 = 'AMPSystemLookup_Regions_Canada' where lookup_custom24 = 'CDN';
update userdata_fields set lookup_custom24 = 'AMPSystemLookup_Regions_World_Long' where lookup_custom24 = 'WORLD-LONG';
update userdata_fields set lookup_custom24 = 'AMPSystemLookup_Regions_World' where lookup_custom24 = 'WORLD';
update userdata_fields set lookup_custom24 = 'AMPSystemLookup_Regions_US_and_Canada' where lookup_custom24 = 'US AND CANADA';
update userdata_fields set lookup_custom25 = 'AMPSystemLookup_Regions_US' where lookup_custom25 = 'US';
update userdata_fields set lookup_custom25 = 'AMPSystemLookup_Regions_Canada' where lookup_custom25 = 'CDN';
update userdata_fields set lookup_custom25 = 'AMPSystemLookup_Regions_World_Long' where lookup_custom25 = 'WORLD-LONG';
update userdata_fields set lookup_custom25 = 'AMPSystemLookup_Regions_World' where lookup_custom25 = 'WORLD';
update userdata_fields set lookup_custom25 = 'AMPSystemLookup_Regions_US_and_Canada' where lookup_custom25 = 'US AND CANADA';
update userdata_fields set lookup_custom26 = 'AMPSystemLookup_Regions_US' where lookup_custom26 = 'US';
update userdata_fields set lookup_custom26 = 'AMPSystemLookup_Regions_Canada' where lookup_custom26 = 'CDN';
update userdata_fields set lookup_custom26 = 'AMPSystemLookup_Regions_World_Long' where lookup_custom26 = 'WORLD-LONG';
update userdata_fields set lookup_custom26 = 'AMPSystemLookup_Regions_World' where lookup_custom26 = 'WORLD';
update userdata_fields set lookup_custom26 = 'AMPSystemLookup_Regions_US_and_Canada' where lookup_custom26 = 'US AND CANADA';
update userdata_fields set lookup_custom27 = 'AMPSystemLookup_Regions_US' where lookup_custom27 = 'US';
update userdata_fields set lookup_custom27 = 'AMPSystemLookup_Regions_Canada' where lookup_custom27 = 'CDN';
update userdata_fields set lookup_custom27 = 'AMPSystemLookup_Regions_World_Long' where lookup_custom27 = 'WORLD-LONG';
update userdata_fields set lookup_custom27 = 'AMPSystemLookup_Regions_World' where lookup_custom27 = 'WORLD';
update userdata_fields set lookup_custom27 = 'AMPSystemLookup_Regions_US_and_Canada' where lookup_custom27 = 'US AND CANADA';
update userdata_fields set lookup_custom28 = 'AMPSystemLookup_Regions_US' where lookup_custom28 = 'US';
update userdata_fields set lookup_custom28 = 'AMPSystemLookup_Regions_Canada' where lookup_custom28 = 'CDN';
update userdata_fields set lookup_custom28 = 'AMPSystemLookup_Regions_World_Long' where lookup_custom28 = 'WORLD-LONG';
update userdata_fields set lookup_custom28 = 'AMPSystemLookup_Regions_World' where lookup_custom28 = 'WORLD';
update userdata_fields set lookup_custom28 = 'AMPSystemLookup_Regions_US_and_Canada' where lookup_custom28 = 'US AND CANADA';
update userdata_fields set lookup_custom29 = 'AMPSystemLookup_Regions_US' where lookup_custom29 = 'US';
update userdata_fields set lookup_custom29 = 'AMPSystemLookup_Regions_Canada' where lookup_custom29 = 'CDN';
update userdata_fields set lookup_custom29 = 'AMPSystemLookup_Regions_World_Long' where lookup_custom29 = 'WORLD-LONG';
update userdata_fields set lookup_custom29 = 'AMPSystemLookup_Regions_World' where lookup_custom29 = 'WORLD';
update userdata_fields set lookup_custom29 = 'AMPSystemLookup_Regions_US_and_Canada' where lookup_custom29 = 'US AND CANADA';
update userdata_fields set lookup_custom30 = 'AMPSystemLookup_Regions_US' where lookup_custom30 = 'US';
update userdata_fields set lookup_custom30 = 'AMPSystemLookup_Regions_Canada' where lookup_custom30 = 'CDN';
update userdata_fields set lookup_custom30 = 'AMPSystemLookup_Regions_World_Long' where lookup_custom30 = 'WORLD-LONG';
update userdata_fields set lookup_custom30 = 'AMPSystemLookup_Regions_World' where lookup_custom30 = 'WORLD';
update userdata_fields set lookup_custom30 = 'AMPSystemLookup_Regions_US_and_Canada' where lookup_custom30 = 'US AND CANADA';
update userdata_fields set lookup_custom31 = 'AMPSystemLookup_Regions_US' where lookup_custom31 = 'US';
update userdata_fields set lookup_custom31 = 'AMPSystemLookup_Regions_Canada' where lookup_custom31 = 'CDN';
update userdata_fields set lookup_custom31 = 'AMPSystemLookup_Regions_World_Long' where lookup_custom31 = 'WORLD-LONG';
update userdata_fields set lookup_custom31 = 'AMPSystemLookup_Regions_World' where lookup_custom31 = 'WORLD';
update userdata_fields set lookup_custom31 = 'AMPSystemLookup_Regions_US_and_Canada' where lookup_custom31 = 'US AND CANADA';
update userdata_fields set lookup_custom32 = 'AMPSystemLookup_Regions_US' where lookup_custom32 = 'US';
update userdata_fields set lookup_custom32 = 'AMPSystemLookup_Regions_Canada' where lookup_custom32 = 'CDN';
update userdata_fields set lookup_custom32 = 'AMPSystemLookup_Regions_World_Long' where lookup_custom32 = 'WORLD-LONG';
update userdata_fields set lookup_custom32 = 'AMPSystemLookup_Regions_World' where lookup_custom32 = 'WORLD';
update userdata_fields set lookup_custom32 = 'AMPSystemLookup_Regions_US_and_Canada' where lookup_custom32 = 'US AND CANADA';
update userdata_fields set lookup_custom33 = 'AMPSystemLookup_Regions_US' where lookup_custom33 = 'US';
update userdata_fields set lookup_custom33 = 'AMPSystemLookup_Regions_Canada' where lookup_custom33 = 'CDN';
update userdata_fields set lookup_custom33 = 'AMPSystemLookup_Regions_World_Long' where lookup_custom33 = 'WORLD-LONG';
update userdata_fields set lookup_custom33 = 'AMPSystemLookup_Regions_World' where lookup_custom33 = 'WORLD';
update userdata_fields set lookup_custom33 = 'AMPSystemLookup_Regions_US_and_Canada' where lookup_custom33 = 'US AND CANADA';
update userdata_fields set lookup_custom34 = 'AMPSystemLookup_Regions_US' where lookup_custom34 = 'US';
update userdata_fields set lookup_custom34 = 'AMPSystemLookup_Regions_Canada' where lookup_custom34 = 'CDN';
update userdata_fields set lookup_custom34 = 'AMPSystemLookup_Regions_World_Long' where lookup_custom34 = 'WORLD-LONG';
update userdata_fields set lookup_custom34 = 'AMPSystemLookup_Regions_World' where lookup_custom34 = 'WORLD';
update userdata_fields set lookup_custom34 = 'AMPSystemLookup_Regions_US_and_Canada' where lookup_custom34 = 'US AND CANADA';
update userdata_fields set lookup_custom35 = 'AMPSystemLookup_Regions_US' where lookup_custom35 = 'US';
update userdata_fields set lookup_custom35 = 'AMPSystemLookup_Regions_Canada' where lookup_custom35 = 'CDN';
update userdata_fields set lookup_custom35 = 'AMPSystemLookup_Regions_World_Long' where lookup_custom35 = 'WORLD-LONG';
update userdata_fields set lookup_custom35 = 'AMPSystemLookup_Regions_World' where lookup_custom35 = 'WORLD';
update userdata_fields set lookup_custom35 = 'AMPSystemLookup_Regions_US_and_Canada' where lookup_custom35 = 'US AND CANADA';
update userdata_fields set lookup_custom36 = 'AMPSystemLookup_Regions_US' where lookup_custom36 = 'US';
update userdata_fields set lookup_custom36 = 'AMPSystemLookup_Regions_Canada' where lookup_custom36 = 'CDN';
update userdata_fields set lookup_custom36 = 'AMPSystemLookup_Regions_World_Long' where lookup_custom36 = 'WORLD-LONG';
update userdata_fields set lookup_custom36 = 'AMPSystemLookup_Regions_World' where lookup_custom36 = 'WORLD';
update userdata_fields set lookup_custom36 = 'AMPSystemLookup_Regions_US_and_Canada' where lookup_custom36 = 'US AND CANADA';
update userdata_fields set lookup_custom37 = 'AMPSystemLookup_Regions_US' where lookup_custom37 = 'US';
update userdata_fields set lookup_custom37 = 'AMPSystemLookup_Regions_Canada' where lookup_custom37 = 'CDN';
update userdata_fields set lookup_custom37 = 'AMPSystemLookup_Regions_World_Long' where lookup_custom37 = 'WORLD-LONG';
update userdata_fields set lookup_custom37 = 'AMPSystemLookup_Regions_World' where lookup_custom37 = 'WORLD';
update userdata_fields set lookup_custom37 = 'AMPSystemLookup_Regions_US_and_Canada' where lookup_custom37 = 'US AND CANADA';
update userdata_fields set lookup_custom38 = 'AMPSystemLookup_Regions_US' where lookup_custom38 = 'US';
update userdata_fields set lookup_custom38 = 'AMPSystemLookup_Regions_Canada' where lookup_custom38 = 'CDN';
update userdata_fields set lookup_custom38 = 'AMPSystemLookup_Regions_World_Long' where lookup_custom38 = 'WORLD-LONG';
update userdata_fields set lookup_custom38 = 'AMPSystemLookup_Regions_World' where lookup_custom38 = 'WORLD';
update userdata_fields set lookup_custom38 = 'AMPSystemLookup_Regions_US_and_Canada' where lookup_custom38 = 'US AND CANADA';
update userdata_fields set lookup_custom39 = 'AMPSystemLookup_Regions_US' where lookup_custom39 = 'US';
update userdata_fields set lookup_custom39 = 'AMPSystemLookup_Regions_Canada' where lookup_custom39 = 'CDN';
update userdata_fields set lookup_custom39 = 'AMPSystemLookup_Regions_World_Long' where lookup_custom39 = 'WORLD-LONG';
update userdata_fields set lookup_custom39 = 'AMPSystemLookup_Regions_World' where lookup_custom39 = 'WORLD';
update userdata_fields set lookup_custom39 = 'AMPSystemLookup_Regions_US_and_Canada' where lookup_custom39 = 'US AND CANADA';
update userdata_fields set lookup_custom40 = 'AMPSystemLookup_Regions_US' where lookup_custom40 = 'US';
update userdata_fields set lookup_custom40 = 'AMPSystemLookup_Regions_Canada' where lookup_custom40 = 'CDN';
update userdata_fields set lookup_custom40 = 'AMPSystemLookup_Regions_World_Long' where lookup_custom40 = 'WORLD-LONG';
update userdata_fields set lookup_custom40 = 'AMPSystemLookup_Regions_World' where lookup_custom40 = 'WORLD';
update userdata_fields set lookup_custom40 = 'AMPSystemLookup_Regions_US_and_Canada' where lookup_custom40 = 'US AND CANADA';
